config/routes.rb
Rails.application.routes.draw do
  root 'players#index'
  resources :players

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players=Player.all
  end
  def show 
  	@player=Player.find(params[:id])
  end
  def new
  	@player=Player.new
  end
  def create
  	@player=Player.new(set_params)
  	if @player.save
  		redirect_to @player
  	else render new
  	end
  end
  
  def edit 
  	@player=Player.find(params[:id])
  end
  def update
  	@player=Player.find(params[:id])
  	if player.update_attributes(set_params)
  		redirect_to @player
  	else render edit
  	end

end
def destroy 
	@player=Player.find(params[:id])
	@player.destroy
	redirect_to players_path
	end
	private 
  def set_params
  	params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= link_to 'New player', new_player_path %>
  	|
  	<%= link_to 'All Player', players_path %>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>


 <div class='form-control'>
 	<%= f.label :nickname %>:
  <%= f.text_field :nickname %>
 </div>

 <div class='form-control'>
 	<%= f.label :rank %>:
  <%= f.text_field :rank %>
 </div>

 <div class='form-control'>
 	<%= f.label :charisma %>:
  <%= f.text_field :charisma %>
 </div>

 <div class='form-control'>
 	<%= f.label :wisdom %>:
  <%= f.text_field :wisdom %>
 </div>

 <div class='form-control'>
 	<%= f.submit 'SOXRANIT' %>:
 </div>
 
 <% end %>

app/views/players/_player.html.erb
<h1><%= link_to player.nickname, player_path(player) %></h1>

app/views/players/edit.html.erb
<h1>edit</h1>
<%= render 'form' %>

app/views/players/index.html.erb
<p>PLAYERS</p>
<%= render @players %>

app/views/players/new.html.erb
<h1>NEW PLAYER</h1>
<%= render 'form' %>

app/views/players/show.html.erb
<h1>Player</h1>
<h2><%=@player.nickname%></h2>
<%= link_to 'Edit', edit_player_path(@player) %>
|
<%= link_to 'Delete', player_path(@player), method: :delete%>
<p>Rank:</p>
<p><%=@player.rank %></p>
<p>Charisma:</p>
<p><%=@player.charisma %></p>
<p>Wisdom:</p>
<p><%=@player.wisdom %></p>